// ignore_for_file: file_names, non_constant_identifier_names, equal_keys_in_map

import 'package:cloud_firestore/cloud_firestore.dart';

import '../../Initiate.dart';

class DatabaseKlinik {
  static FirebaseFirestore firestore = FirebaseFirestore.instance;

  static CollectionReference userdata = firestore.collection('user');
  static CollectionReference RSGM = firestore.collection('RSGM');
  static CollectionReference console = firestore.collection('console');
  static CollectionReference Klinik = firestore.collection('Klinik');

  static CollectionReference Alat = firestore.collection('Alat');
  static CollectionReference Bahan = firestore.collection('Bahan');
  static CollectionReference Dosen = firestore.collection('Dosen');

  static Future<void> AccKlinik(
    String email,
    bool acc,
  ) async {
    await userdata.doc(email).update(
      {
        'ACCADMIN': acc,
      },
    );
  }

  static Future<void> TambahDataRekamMedis(
    String NamaKlinik,
  ) async {
    await Klinik.doc(NamaKlinik).update(
      {
        'NoRM': FieldValue.increment(1),
      },
    );
  }

  static Future<void> RegistrasiDataRekamMedis(
    String NamaKlinik,
    String nomorRM,
    String identitas,
    String nomoridentitas,
    String gambarKRS,
    String nama,
    String tempatlahir,
    String gender,
    String? tanggallahir,
    String? bulanlahir,
    String? tahunlahir,
    String alamat,
    String noHP,
    String pekerjaan,
    String golongandarah,
    String statuspernikahan,
    String agama,
    String pendidikan,
    String warganegara,
    String tanggal,
    bulan,
    tahun,
  ) async {
    await Klinik.doc(NamaKlinik).collection('RekamMedis').doc().set(
      {
        'NomorRekamMedis': nomorRM,
        'identitas': identitas,
        'no_identitas': nomoridentitas,
        'gambarKRS': gambarKRS,
        'nama': nama,
        'tempatlahir': tempatlahir,
        'gender': gender,
        'tanggallahir': tanggallahir,
        'bulanlahir': bulanlahir,
        'tahunlahir': tahunlahir,
        'alamat': alamat,
        'noHP': noHP,
        'pekerjaan': pekerjaan,
        'golongandarah': golongandarah,
        'statuspernikahan': statuspernikahan,
        'agama': agama,
        'pendidikan': pendidikan,
        'warganegara': warganegara,
        'kunjungan': 1,
        'banyakrencanaperawatan': 0,
        'banyakpemeriksaanpenunjang': 0,
        'banyaktindakanperawatan': 0,
        'NamaKlinik': NamaKlinik,
        'WaktuDaftar': FieldValue.serverTimestamp(),
      },
    );
  }

  static Future<void> RMPutihsetOdontogram(
    String NamaKlinik,
    String nomorRM,
    String Gigi11atas,
    Gigi11tengah,
    Gigi11bawah,
    Gigi11m,
    Gigi11mcar,
    Gigi11d,
    Gigi11dcar,
    Gigi11v,
    Gigi11vcar,
    Gigi11l,
    Gigi11lcar,
    //////////////////////
    Gigi12atas,
    Gigi12tengah,
    Gigi12bawah,
    Gigi12m,
    Gigi12mcar,
    Gigi12d,
    Gigi12dcar,
    Gigi12v,
    Gigi12vcar,
    Gigi12l,
    Gigi12lcar,
    //////////////////////
    Gigi13atas,
    Gigi13tengah,
    Gigi13bawah,
    Gigi13m,
    Gigi13mcar,
    Gigi13d,
    Gigi13dcar,
    Gigi13v,
    Gigi13vcar,
    Gigi13l,
    Gigi13lcar,
    //////////////////
    Gigi14atas,
    Gigi14tengah,
    Gigi14bawah,
    Gigi14m,
    Gigi14mcar,
    Gigi14d,
    Gigi14dcar,
    Gigi14o,
    Gigi14ocar,
    Gigi14v,
    Gigi14vcar,
    Gigi14l,
    Gigi14lcar,
    ///////
    Gigi15atas,
    Gigi15tengah,
    Gigi15bawah,
    Gigi15m,
    Gigi15mcar,
    Gigi15d,
    Gigi15dcar,
    Gigi15o,
    Gigi15ocar,
    Gigi15v,
    Gigi15vcar,
    Gigi15l,
    Gigi15lcar,
    ///////
    Gigi16atas,
    Gigi16tengah,
    Gigi16bawah,
    Gigi16m,
    Gigi16mcar,
    Gigi16d,
    Gigi16dcar,
    Gigi16o,
    Gigi16ocar,
    Gigi16v,
    Gigi16vcar,
    Gigi16l,
    Gigi16lcar,
    ///////
    Gigi17atas,
    Gigi17tengah,
    Gigi17bawah,
    Gigi17m,
    Gigi17mcar,
    Gigi17d,
    Gigi17dcar,
    Gigi17o,
    Gigi17ocar,
    Gigi17v,
    Gigi17vcar,
    Gigi17l,
    Gigi17lcar,
    ///////
    Gigi18atas,
    Gigi18tengah,
    Gigi18bawah,
    Gigi18m,
    Gigi18mcar,
    Gigi18d,
    Gigi18dcar,
    Gigi18o,
    Gigi18ocar,
    Gigi18v,
    Gigi18vcar,
    Gigi18l,
    Gigi18lcar,
    ///////////////////////////////////////////////////////////////
    ////
    ///////////////////////////////////////////////////////////////
    Gigi21atas,
    Gigi21tengah,
    Gigi21bawah,
    Gigi21m,
    Gigi21mcar,
    Gigi21d,
    Gigi21dcar,
    Gigi21v,
    Gigi21vcar,
    Gigi21l,
    Gigi21lcar,
    //////////////////////
    Gigi22atas,
    Gigi22tengah,
    Gigi22bawah,
    Gigi22m,
    Gigi22mcar,
    Gigi22d,
    Gigi22dcar,
    Gigi22v,
    Gigi22vcar,
    Gigi22l,
    Gigi22lcar,
    //////////////////////
    Gigi23atas,
    Gigi23tengah,
    Gigi23bawah,
    Gigi23m,
    Gigi23mcar,
    Gigi23d,
    Gigi23dcar,
    Gigi23v,
    Gigi23vcar,
    Gigi23l,
    Gigi23lcar,
    //////////////////
    Gigi24atas,
    Gigi24tengah,
    Gigi24bawah,
    Gigi24m,
    Gigi24mcar,
    Gigi24d,
    Gigi24dcar,
    Gigi24o,
    Gigi24ocar,
    Gigi24v,
    Gigi24vcar,
    Gigi24l,
    Gigi24lcar,
    ///////
    Gigi25atas,
    Gigi25tengah,
    Gigi25bawah,
    Gigi25m,
    Gigi25mcar,
    Gigi25d,
    Gigi25dcar,
    Gigi25o,
    Gigi25ocar,
    Gigi25v,
    Gigi25vcar,
    Gigi25l,
    Gigi25lcar,
    ///////
    Gigi26atas,
    Gigi26tengah,
    Gigi26bawah,
    Gigi26m,
    Gigi26mcar,
    Gigi26d,
    Gigi26dcar,
    Gigi26o,
    Gigi26ocar,
    Gigi26v,
    Gigi26vcar,
    Gigi26l,
    Gigi26lcar,
    ///////
    Gigi27atas,
    Gigi27tengah,
    Gigi27bawah,
    Gigi27m,
    Gigi27mcar,
    Gigi27d,
    Gigi27dcar,
    Gigi27o,
    Gigi27ocar,
    Gigi27v,
    Gigi27vcar,
    Gigi27l,
    Gigi27lcar,
    ///////
    Gigi28atas,
    Gigi28tengah,
    Gigi28bawah,
    Gigi28m,
    Gigi28mcar,
    Gigi28d,
    Gigi28dcar,
    Gigi28o,
    Gigi28ocar,
    Gigi28v,
    Gigi28vcar,
    Gigi28l,
    Gigi28lcar,
    /////////////////////////////////////////////////////////////////////////
    //////////////
    /////////////////////////////////////////////////////////////////////////////////////////////
    Gigi31atas,
    Gigi31tengah,
    Gigi31bawah,
    Gigi31m,
    Gigi31mcar,
    Gigi31d,
    Gigi31dcar,
    Gigi31v,
    Gigi31vcar,
    Gigi31l,
    Gigi31lcar,
    //////////////////////
    Gigi32atas,
    Gigi32tengah,
    Gigi32bawah,
    Gigi32m,
    Gigi32mcar,
    Gigi32d,
    Gigi32dcar,
    Gigi32v,
    Gigi32vcar,
    Gigi32l,
    Gigi32lcar,
    //////////////////////
    Gigi33atas,
    Gigi33tengah,
    Gigi33bawah,
    Gigi33m,
    Gigi33mcar,
    Gigi33d,
    Gigi33dcar,
    Gigi33v,
    Gigi33vcar,
    Gigi33l,
    Gigi33lcar,
    //////////////////
    Gigi34atas,
    Gigi34tengah,
    Gigi34bawah,
    Gigi34m,
    Gigi34mcar,
    Gigi34d,
    Gigi34dcar,
    Gigi34o,
    Gigi34ocar,
    Gigi34v,
    Gigi34vcar,
    Gigi34l,
    Gigi34lcar,
    ///////
    Gigi35atas,
    Gigi35tengah,
    Gigi35bawah,
    Gigi35m,
    Gigi35mcar,
    Gigi35d,
    Gigi35o,
    Gigi35ocar,
    Gigi35dcar,
    Gigi35v,
    Gigi35vcar,
    Gigi35l,
    Gigi35lcar,
    ///////
    Gigi36atas,
    Gigi36tengah,
    Gigi36bawah,
    Gigi36m,
    Gigi36mcar,
    Gigi36d,
    Gigi36dcar,
    Gigi36o,
    Gigi36ocar,
    Gigi36v,
    Gigi36vcar,
    Gigi36l,
    Gigi36lcar,
    ///////
    Gigi37atas,
    Gigi37tengah,
    Gigi37bawah,
    Gigi37m,
    Gigi37mcar,
    Gigi37d,
    Gigi37dcar,
    Gigi37o,
    Gigi37ocar,
    Gigi37v,
    Gigi37vcar,
    Gigi37l,
    Gigi37lcar,
    ///////
    Gigi38atas,
    Gigi38tengah,
    Gigi38bawah,
    Gigi38m,
    Gigi38mcar,
    Gigi38d,
    Gigi38dcar,
    Gigi38o,
    Gigi38ocar,
    Gigi38v,
    Gigi38vcar,
    Gigi38l,
    Gigi38lcar,
    ///////////////////////////////////////////////////////////////
    ////
    ///////////////////////////////////////////////////////////////
    Gigi41atas,
    Gigi41tengah,
    Gigi41bawah,
    Gigi41m,
    Gigi41mcar,
    Gigi41d,
    Gigi41dcar,
    Gigi41v,
    Gigi41vcar,
    Gigi41l,
    Gigi41lcar,
    //////////////////////
    Gigi42atas,
    Gigi42tengah,
    Gigi42bawah,
    Gigi42m,
    Gigi42mcar,
    Gigi42d,
    Gigi42dcar,
    Gigi42v,
    Gigi42vcar,
    Gigi42l,
    Gigi42lcar,
    //////////////////////
    Gigi43atas,
    Gigi43tengah,
    Gigi43bawah,
    Gigi43m,
    Gigi43mcar,
    Gigi43d,
    Gigi43dcar,
    Gigi43v,
    Gigi43vcar,
    Gigi43l,
    Gigi43lcar,
    //////////////////
    Gigi44atas,
    Gigi44tengah,
    Gigi44bawah,
    Gigi44m,
    Gigi44mcar,
    Gigi44d,
    Gigi44dcar,
    Gigi44o,
    Gigi44ocar,
    Gigi44v,
    Gigi44vcar,
    Gigi44l,
    Gigi44lcar,
    ///////
    Gigi45atas,
    Gigi45tengah,
    Gigi45bawah,
    Gigi45m,
    Gigi45mcar,
    Gigi45d,
    Gigi45dcar,
    Gigi45o,
    Gigi45ocar,
    Gigi45v,
    Gigi45vcar,
    Gigi45l,
    Gigi45lcar,
    ///////
    Gigi46atas,
    Gigi46tengah,
    Gigi46bawah,
    Gigi46m,
    Gigi46mcar,
    Gigi46d,
    Gigi46dcar,
    Gigi46o,
    Gigi46ocar,
    Gigi46v,
    Gigi46vcar,
    Gigi46l,
    Gigi46lcar,
    ///////
    Gigi47atas,
    Gigi47tengah,
    Gigi47bawah,
    Gigi47m,
    Gigi47mcar,
    Gigi47d,
    Gigi47dcar,
    Gigi47o,
    Gigi47ocar,
    Gigi47v,
    Gigi47vcar,
    Gigi47l,
    Gigi47lcar,
    ///////
    Gigi48atas,
    Gigi48tengah,
    Gigi48bawah,
    Gigi48m,
    Gigi48mcar,
    Gigi48d,
    Gigi48dcar,
    Gigi48o,
    Gigi48ocar,
    Gigi48v,
    Gigi48vcar,
    Gigi48l,
    Gigi48lcar,
    desidui51,
    desidui52,
    desidui53,
    desidui54,
    desidui55,
    desidui61,
    desidui62,
    desidui63,
    desidui64,
    desidui65,
    desidui71,
    desidui72,
    desidui73,
    desidui74,
    desidui75,
    desidui81,
    desidui82,
    desidui83,
    desidui84,
    desidui85,
  ) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(nomorRM)
        .collection('Odontogram')
        .doc('Odontogram')
        .set(
      {
        'Gigi11atas': Gigi11atas,
        'Gigi11tengah': Gigi11tengah,
        'Gigi11bawah': Gigi11bawah,
        'Gigi11m': Gigi11m,
        'Gigi11mcar': Gigi11mcar,
        'Gigi11d': Gigi11d,
        'Gigi11dcar': Gigi11dcar,
        'Gigi11v': Gigi11v,
        'Gigi11vcar': Gigi11vcar,
        'Gigi11l': Gigi11l,
        'Gigi11lcar': Gigi11lcar,
        'Gigi12atas': Gigi12atas,
        'Gigi12tengah': Gigi12tengah,
        'Gigi12bawah': Gigi12bawah,
        'Gigi12m': Gigi12m,
        'Gigi12mcar': Gigi12mcar,
        'Gigi12d': Gigi12d,
        'Gigi12dcar': Gigi12dcar,
        'Gigi12v': Gigi12v,
        'Gigi12vcar': Gigi12vcar,
        'Gigi12l': Gigi12l,
        'Gigi12lcar': Gigi12lcar,
        'Gigi13atas': Gigi13atas,
        'Gigi13tengah': Gigi13tengah,
        'Gigi13bawah': Gigi13bawah,
        'Gigi13m': Gigi13m,
        'Gigi13mcar': Gigi13mcar,
        'Gigi13d': Gigi13d,
        'Gigi13dcar': Gigi13dcar,
        'Gigi13v': Gigi13v,
        'Gigi13vcar': Gigi13vcar,
        'Gigi13l': Gigi13l,
        'Gigi13lcar': Gigi13lcar,
        'Gigi14atas': Gigi14atas,
        'Gigi14tengah': Gigi14tengah,
        'Gigi14bawah': Gigi14bawah,
        'Gigi14m': Gigi14m,
        'Gigi14mcar': Gigi14mcar,
        'Gigi14d': Gigi14d,
        'Gigi14dcar': Gigi14dcar,
        'Gigi14o': Gigi14o,
        'Gigi14ocar': Gigi14ocar,
        'Gigi14v': Gigi14v,
        'Gigi14vcar': Gigi14vcar,
        'Gigi14l': Gigi14l,
        'Gigi14lcar': Gigi14lcar,
        'Gigi15atas': Gigi15atas,
        'Gigi15tengah': Gigi15tengah,
        'Gigi15bawah': Gigi15bawah,
        'Gigi15m': Gigi15m,
        'Gigi15mcar': Gigi15mcar,
        'Gigi15d': Gigi15d,
        'Gigi15dcar': Gigi15dcar,
        'Gigi15o': Gigi15o,
        'Gigi15ocar': Gigi15ocar,
        'Gigi15v': Gigi15v,
        'Gigi15vcar': Gigi15vcar,
        'Gigi15l': Gigi15l,
        'Gigi15lcar': Gigi15lcar,
        'Gigi16atas': Gigi16atas,
        'Gigi16tengah': Gigi16tengah,
        'Gigi16bawah': Gigi16bawah,
        'Gigi16m': Gigi16m,
        'Gigi16mcar': Gigi16mcar,
        'Gigi16d': Gigi16d,
        'Gigi16dcar': Gigi16dcar,
        'Gigi16o': Gigi16o,
        'Gigi16ocar': Gigi16ocar,
        'Gigi16v': Gigi16v,
        'Gigi16vcar': Gigi16vcar,
        'Gigi16l': Gigi16l,
        'Gigi16lcar': Gigi16lcar,
        'Gigi17atas': Gigi17atas,
        'Gigi17tengah': Gigi17tengah,
        'Gigi17bawah': Gigi17bawah,
        'Gigi17m': Gigi17m,
        'Gigi17mcar': Gigi17mcar,
        'Gigi17d': Gigi17d,
        'Gigi17dcar': Gigi17dcar,
        'Gigi17o': Gigi17o,
        'Gigi17ocar': Gigi17ocar,
        'Gigi17v': Gigi17v,
        'Gigi17vcar': Gigi17vcar,
        'Gigi17l': Gigi17l,
        'Gigi17lcar': Gigi17lcar,
        'Gigi18atas': Gigi18atas,
        'Gigi18tengah': Gigi18tengah,
        'Gigi18bawah': Gigi18bawah,
        'Gigi18m': Gigi18m,
        'Gigi18mcar': Gigi18mcar,
        'Gigi18d': Gigi18d,
        'Gigi18dcar': Gigi18dcar,
        'Gigi18o': Gigi18o,
        'Gigi18ocar': Gigi18ocar,
        'Gigi18v': Gigi18v,
        'Gigi18vcar': Gigi18vcar,
        'Gigi18l': Gigi18l,
        'Gigi18lcar': Gigi18lcar,
        'Gigi21atas': Gigi21atas,
        'Gigi21tengah': Gigi21tengah,
        'Gigi21bawah': Gigi21bawah,
        'Gigi21m': Gigi21m,
        'Gigi21mcar': Gigi21mcar,
        'Gigi21d': Gigi21d,
        'Gigi21dcar': Gigi21dcar,
        'Gigi21v': Gigi21v,
        'Gigi21vcar': Gigi21vcar,
        'Gigi21l': Gigi21l,
        'Gigi21lcar': Gigi21lcar,
        'Gigi22atas': Gigi22atas,
        'Gigi22tengah': Gigi22tengah,
        'Gigi22bawah': Gigi22bawah,
        'Gigi22m': Gigi22m,
        'Gigi22mcar': Gigi22mcar,
        'Gigi22d': Gigi22d,
        'Gigi22dcar': Gigi22dcar,
        'Gigi22v': Gigi22v,
        'Gigi22vcar': Gigi22vcar,
        'Gigi22l': Gigi22l,
        'Gigi22lcar': Gigi22lcar,
        'Gigi23atas': Gigi23atas,
        'Gigi23tengah': Gigi23tengah,
        'Gigi23bawah': Gigi23bawah,
        'Gigi23m': Gigi23m,
        'Gigi23mcar': Gigi23mcar,
        'Gigi23d': Gigi23d,
        'Gigi23dcar': Gigi23dcar,
        'Gigi23v': Gigi23v,
        'Gigi23vcar': Gigi23vcar,
        'Gigi23l': Gigi23l,
        'Gigi23lcar': Gigi23lcar,
        'Gigi24atas': Gigi24atas,
        'Gigi24tengah': Gigi24tengah,
        'Gigi24bawah': Gigi24bawah,
        'Gigi24m': Gigi24m,
        'Gigi24mcar': Gigi24mcar,
        'Gigi24d': Gigi24d,
        'Gigi24dcar': Gigi24dcar,
        'Gigi24o': Gigi24o,
        'Gigi24ocar': Gigi24ocar,
        'Gigi24v': Gigi24v,
        'Gigi24vcar': Gigi24vcar,
        'Gigi24l': Gigi24l,
        'Gigi24lcar': Gigi24lcar,
        'Gigi25atas': Gigi25atas,
        'Gigi25tengah': Gigi25tengah,
        'Gigi25bawah': Gigi25bawah,
        'Gigi25m': Gigi25m,
        'Gigi25mcar': Gigi25mcar,
        'Gigi25d': Gigi25d,
        'Gigi25dcar': Gigi25dcar,
        'Gigi25o': Gigi25o,
        'Gigi25ocar': Gigi25ocar,
        'Gigi25v': Gigi25v,
        'Gigi25vcar': Gigi25vcar,
        'Gigi25l': Gigi25l,
        'Gigi25lcar': Gigi25lcar,
        'Gigi26atas': Gigi26atas,
        'Gigi26tengah': Gigi26tengah,
        'Gigi26bawah': Gigi26bawah,
        'Gigi26m': Gigi26m,
        'Gigi26mcar': Gigi26mcar,
        'Gigi26d': Gigi26d,
        'Gigi26dcar': Gigi26dcar,
        'Gigi26o': Gigi26o,
        'Gigi26ocar': Gigi26ocar,
        'Gigi26v': Gigi26v,
        'Gigi26vcar': Gigi26vcar,
        'Gigi26l': Gigi26l,
        'Gigi26lcar': Gigi26lcar,
        'Gigi27atas': Gigi27atas,
        'Gigi27tengah': Gigi27tengah,
        'Gigi27bawah': Gigi27bawah,
        'Gigi27m': Gigi27m,
        'Gigi27mcar': Gigi27mcar,
        'Gigi27d': Gigi27d,
        'Gigi27dcar': Gigi27dcar,
        'Gigi27o': Gigi27o,
        'Gigi27ocar': Gigi27ocar,
        'Gigi27v': Gigi27v,
        'Gigi27vcar': Gigi27vcar,
        'Gigi27l': Gigi27l,
        'Gigi27lcar': Gigi27lcar,
        'Gigi28atas': Gigi28atas,
        'Gigi28tengah': Gigi28tengah,
        'Gigi28bawah': Gigi28bawah,
        'Gigi28m': Gigi28m,
        'Gigi28mcar': Gigi28mcar,
        'Gigi28d': Gigi28d,
        'Gigi28dcar': Gigi28dcar,
        'Gigi28o': Gigi28o,
        'Gigi28ocar': Gigi28ocar,
        'Gigi28v': Gigi28v,
        'Gigi28vcar': Gigi28vcar,
        'Gigi28l': Gigi28l,
        'Gigi28lcar': Gigi28lcar,
        'Gigi31atas': Gigi31atas,
        'Gigi31tengah': Gigi31tengah,
        'Gigi31bawah': Gigi31bawah,
        'Gigi31m': Gigi31m,
        'Gigi31mcar': Gigi31mcar,
        'Gigi31d': Gigi31d,
        'Gigi31dcar': Gigi31dcar,
        'Gigi31v': Gigi31v,
        'Gigi31vcar': Gigi31vcar,
        'Gigi31l': Gigi31l,
        'Gigi31lcar': Gigi31lcar,
        'Gigi32atas': Gigi32atas,
        'Gigi32tengah': Gigi32tengah,
        'Gigi32bawah': Gigi32bawah,
        'Gigi32m': Gigi32m,
        'Gigi32mcar': Gigi32mcar,
        'Gigi32d': Gigi32d,
        'Gigi32dcar': Gigi32dcar,
        'Gigi32v': Gigi32v,
        'Gigi32vcar': Gigi32vcar,
        'Gigi32l': Gigi32l,
        'Gigi32lcar': Gigi32lcar,
        'Gigi33atas': Gigi33atas,
        'Gigi33tengah': Gigi33tengah,
        'Gigi33bawah': Gigi33bawah,
        'Gigi33m': Gigi33m,
        'Gigi33mcar': Gigi33mcar,
        'Gigi33d': Gigi33d,
        'Gigi33dcar': Gigi33dcar,
        'Gigi33v': Gigi33v,
        'Gigi33vcar': Gigi33vcar,
        'Gigi33l': Gigi33l,
        'Gigi33lcar': Gigi33lcar,
        'Gigi34atas': Gigi34atas,
        'Gigi34tengah': Gigi34tengah,
        'Gigi34bawah': Gigi34bawah,
        'Gigi34m': Gigi34m,
        'Gigi34mcar': Gigi34mcar,
        'Gigi34d': Gigi34d,
        'Gigi34dcar': Gigi34dcar,
        'Gigi34o': Gigi34o,
        'Gigi34ocar': Gigi34ocar,
        'Gigi34v': Gigi34v,
        'Gigi34vcar': Gigi34vcar,
        'Gigi34l': Gigi34l,
        'Gigi34lcar': Gigi34lcar,
        'Gigi35atas': Gigi35atas,
        'Gigi35tengah': Gigi35tengah,
        'Gigi35bawah': Gigi35bawah,
        'Gigi35m': Gigi35m,
        'Gigi35mcar': Gigi35mcar,
        'Gigi35d': Gigi35d,
        'Gigi35o': Gigi35o,
        'Gigi35ocar': Gigi35ocar,
        'Gigi35dcar': Gigi35dcar,
        'Gigi35v': Gigi35v,
        'Gigi35vcar': Gigi35vcar,
        'Gigi35l': Gigi35l,
        'Gigi35lcar': Gigi35lcar,
        'Gigi36atas': Gigi36atas,
        'Gigi36tengah': Gigi36tengah,
        'Gigi36bawah': Gigi36bawah,
        'Gigi36m': Gigi36m,
        'Gigi36mcar': Gigi36mcar,
        'Gigi36d': Gigi36d,
        'Gigi36dcar': Gigi36dcar,
        'Gigi36o': Gigi36o,
        'Gigi36ocar': Gigi36ocar,
        'Gigi36v': Gigi36v,
        'Gigi36vcar': Gigi36vcar,
        'Gigi36l': Gigi36l,
        'Gigi36lcar': Gigi36lcar,
        'Gigi37atas': Gigi37atas,
        'Gigi37tengah': Gigi37tengah,
        'Gigi37bawah': Gigi37bawah,
        'Gigi37m': Gigi37m,
        'Gigi37mcar': Gigi37mcar,
        'Gigi37d': Gigi37d,
        'Gigi37dcar': Gigi37dcar,
        'Gigi37o': Gigi37o,
        'Gigi37ocar': Gigi37ocar,
        'Gigi37v': Gigi37v,
        'Gigi37vcar': Gigi37vcar,
        'Gigi37l': Gigi37l,
        'Gigi37lcar': Gigi37lcar,
        'Gigi38atas': Gigi38atas,
        'Gigi38tengah': Gigi38tengah,
        'Gigi38bawah': Gigi38bawah,
        'Gigi38m': Gigi38m,
        'Gigi38mcar': Gigi38mcar,
        'Gigi38d': Gigi38d,
        'Gigi38dcar': Gigi38dcar,
        'Gigi38o': Gigi38o,
        'Gigi38ocar': Gigi38ocar,
        'Gigi38v': Gigi38v,
        'Gigi38vcar': Gigi38vcar,
        'Gigi38l': Gigi38l,
        'Gigi38lcar': Gigi38lcar,
        'Gigi41atas': Gigi41atas,
        'Gigi41tengah': Gigi41tengah,
        'Gigi41bawah': Gigi41bawah,
        'Gigi41m': Gigi41m,
        'Gigi41mcar': Gigi41mcar,
        'Gigi41d': Gigi41d,
        'Gigi41dcar': Gigi41dcar,
        'Gigi41v': Gigi41v,
        'Gigi41vcar': Gigi41vcar,
        'Gigi41l': Gigi41l,
        'Gigi41lcar': Gigi41lcar,
        'Gigi42atas': Gigi42atas,
        'Gigi42tengah': Gigi42tengah,
        'Gigi42bawah': Gigi42bawah,
        'Gigi42m': Gigi42m,
        'Gigi42mcar': Gigi42mcar,
        'Gigi42d': Gigi42d,
        'Gigi42dcar': Gigi42dcar,
        'Gigi42v': Gigi42v,
        'Gigi42vcar': Gigi42vcar,
        'Gigi42l': Gigi42l,
        'Gigi42lcar': Gigi42lcar,
        'Gigi43atas': Gigi43atas,
        'Gigi43tengah': Gigi43tengah,
        'Gigi43bawah': Gigi43bawah,
        'Gigi43m': Gigi43m,
        'Gigi43mcar': Gigi43mcar,
        'Gigi43d': Gigi43d,
        'Gigi43dcar': Gigi43dcar,
        'Gigi43v': Gigi43v,
        'Gigi43vcar': Gigi43vcar,
        'Gigi43l': Gigi43l,
        'Gigi43lcar': Gigi43lcar,
        'Gigi44atas': Gigi44atas,
        'Gigi44tengah': Gigi44tengah,
        'Gigi44bawah': Gigi44bawah,
        'Gigi44m': Gigi44m,
        'Gigi44mcar': Gigi44mcar,
        'Gigi44d': Gigi44d,
        'Gigi44dcar': Gigi44dcar,
        'Gigi44o': Gigi44o,
        'Gigi44ocar': Gigi44ocar,
        'Gigi44v': Gigi44v,
        'Gigi44vcar': Gigi44vcar,
        'Gigi44l': Gigi44l,
        'Gigi44lcar': Gigi44lcar,
        'Gigi45atas': Gigi45atas,
        'Gigi45tengah': Gigi45tengah,
        'Gigi45bawah': Gigi45bawah,
        'Gigi45m': Gigi45m,
        'Gigi45mcar': Gigi45mcar,
        'Gigi45d': Gigi45d,
        'Gigi45dcar': Gigi45dcar,
        'Gigi45o': Gigi45o,
        'Gigi45ocar': Gigi45ocar,
        'Gigi45v': Gigi45v,
        'Gigi45vcar': Gigi45vcar,
        'Gigi45l': Gigi45l,
        'Gigi45lcar': Gigi45lcar,
        'Gigi46atas': Gigi46atas,
        'Gigi46tengah': Gigi46tengah,
        'Gigi46bawah': Gigi46bawah,
        'Gigi46m': Gigi46m,
        'Gigi46mcar': Gigi46mcar,
        'Gigi46d': Gigi46d,
        'Gigi46dcar': Gigi46dcar,
        'Gigi46o': Gigi46o,
        'Gigi46ocar': Gigi46ocar,
        'Gigi46v': Gigi46v,
        'Gigi46vcar': Gigi46vcar,
        'Gigi46l': Gigi46l,
        'Gigi46lcar': Gigi46lcar,
        'Gigi47atas': Gigi47atas,
        'Gigi47tengah': Gigi47tengah,
        'Gigi47bawah': Gigi47bawah,
        'Gigi47m': Gigi47m,
        'Gigi47mcar': Gigi47mcar,
        'Gigi47d': Gigi47d,
        'Gigi47dcar': Gigi47dcar,
        'Gigi47o': Gigi47o,
        'Gigi47ocar': Gigi47ocar,
        'Gigi47v': Gigi47v,
        'Gigi47vcar': Gigi47vcar,
        'Gigi47l': Gigi47l,
        'Gigi47lcar': Gigi47lcar,
        'Gigi48atas': Gigi48atas,
        'Gigi48tengah': Gigi48tengah,
        'Gigi48bawah': Gigi48bawah,
        'Gigi48m': Gigi48m,
        'Gigi48mcar': Gigi48mcar,
        'Gigi48d': Gigi48d,
        'Gigi48dcar': Gigi48dcar,
        'Gigi48o': Gigi48o,
        'Gigi48ocar': Gigi48ocar,
        'Gigi48v': Gigi48v,
        'Gigi48vcar': Gigi48vcar,
        'Gigi48l': Gigi48l,
        'Gigi48lcar': Gigi48lcar,
        'desidui51': desidui51,
        'desidui52': desidui52,
        'desidui53': desidui53,
        'desidui54': desidui54,
        'desidui55': desidui55,
        'desidui61': desidui61,
        'desidui62': desidui62,
        'desidui63': desidui63,
        'desidui64': desidui64,
        'desidui65': desidui65,
        'desidui71': desidui71,
        'desidui72': desidui72,
        'desidui73': desidui73,
        'desidui74': desidui74,
        'desidui75': desidui75,
        'desidui81': desidui81,
        'desidui82': desidui82,
        'desidui83': desidui83,
        'desidui84': desidui84,
        'desidui85': desidui85,
      },
    );
  }

  static Future<void> ISIRMLesi(
    String NoRM,
    String lesi,
  ) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(NoRM)
        .collection('Lesi')
        .doc('Lesi')
        .set(
      {
        'lesi': lesi,
      },
    );
  }

  static Future<void> RMPutihsetOHI(
      String namarsgm,
      String nomorRM,
      String tanggal,
      bulan,
      tahun,
      int debrisbukalmaxilakanan,
      int debrisbukalmaxilaant,
      int debrisbukalmaxilakiri,
      int debrispalatalmaxilakanan,
      int debrispalatalmaxilaant,
      int debrispalatalmaxilakiri,
      int debrisbukalmandibulakanan,
      int debrisbukalmandibulaant,
      int debrisbukalmandibulakiri,
      int debrislingualmandibulakanan,
      int debrislingualmandibulaant,
      int debrislingualmandibulakiri,
      int kalkulusbukalmaxilakanan,
      int kalkulusbukalmaxilaant,
      int kalkulusbukalmaxilakiri,
      int kalkuluspalatalmaxilakanan,
      int kalkuluspalatalmaxilaant,
      int kalkuluspalatalmaxilakiri,
      int kalkulusbukalmandibulakanan,
      int kalkulusbukalmandibulaant,
      int kalkulusbukalmandibulakiri,
      int kalkuluslingualmandibulakanan,
      int kalkuluslingualmandibulaant,
      int kalkuluslingualmandibulakiri) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(nomorRM)
        .collection('OHI')
        .doc('$tanggal $bulan $tahun')
        .set({
      'debrismaxilabukalkanan': debrisbukalmaxilakanan,
      'debrismaxilabukalant': debrisbukalmaxilaant,
      'debrismaxilabukalkiri': debrisbukalmaxilakiri,
      'debrismaxilapalatalkanan': debrispalatalmaxilakanan,
      'debrismaxilapalatalant': debrispalatalmaxilaant,
      'debrismaxilapalatalkiri': debrispalatalmaxilakiri,
      'debrismandibulabukalkanan': debrisbukalmandibulakanan,
      'debrismandibulabukalant': debrisbukalmandibulaant,
      'debrismandibulabukalkiri': debrisbukalmandibulakiri,
      'debrismandibulalingualkanan': debrislingualmandibulakanan,
      'debrismandibulalingualant': debrislingualmandibulaant,
      'debrismandibulalingualkiri': debrislingualmandibulakiri,
      'calculusmaxilabukalkanan': kalkulusbukalmaxilakanan,
      'calculusmaxilabukalant': kalkulusbukalmaxilaant,
      'calculusmaxilabukalkiri': kalkulusbukalmaxilakiri,
      'calculusmaxilapalatalkanan': kalkuluspalatalmaxilakanan,
      'calculusmaxilapalatalant': kalkuluspalatalmaxilaant,
      'calculusmaxilapalatalkiri': kalkuluspalatalmaxilakiri,
      'calculusmandibulabukalkanan': kalkulusbukalmandibulakanan,
      'calculusmandibulabukalant': kalkulusbukalmandibulaant,
      'calculusmandibulabukalkiri': kalkulusbukalmandibulakiri,
      'calculusmandibulalingualkanan': kalkuluslingualmandibulakanan,
      'calculusmandibulalingualant': kalkuluslingualmandibulaant,
      'calculusmandibulalingualkiri': kalkuluslingualmandibulakiri,
      'Tanggal': '$tanggal $bulan $tahun',
      'Done': false,
    });
  }

  static Future<void> RMPutihsetGI(
    String namarsgm,
    String nomorRM,
    String tanggal,
    bulan,
    tahun,
    int G11,
    G12,
    G13,
    G14,
    G15,
    G16,
    G17,
    G18,
    G21,
    G22,
    G23,
    G24,
    G25,
    G26,
    G27,
    G28,
    G31,
    G32,
    G33,
    G34,
    G35,
    G36,
    G37,
    G38,
    G41,
    G42,
    G43,
    G44,
    G45,
    G46,
    G47,
    G48,
    BanyakGigi,
  ) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(nomorRM)
        .collection('GI')
        .doc('$tanggal $bulan $tahun')
        .set(
      {
        'G11': G11,
        'G12': G12,
        'G13': G13,
        'G14': G14,
        'G15': G15,
        'G16': G16,
        'G17': G17,
        'G18': G18,
        'G21': G21,
        'G22': G22,
        'G23': G23,
        'G24': G24,
        'G25': G25,
        'G26': G26,
        'G27': G27,
        'G28': G28,
        'G31': G31,
        'G32': G32,
        'G33': G33,
        'G34': G34,
        'G35': G35,
        'G36': G36,
        'G37': G37,
        'G38': G38,
        'G41': G41,
        'G42': G42,
        'G43': G43,
        'G44': G44,
        'G45': G45,
        'G46': G46,
        'G47': G47,
        'G48': G48,
        'BanyakGigi': BanyakGigi,
        'Tanggal': '$tanggal $bulan $tahun',
      },
    );
  }

  static Future<void> RMPutihsetMalposisi(
    String namarsgm,
    String nomorRM,
    String tanggal,
    bulan,
    tahun,
    String G11,
    G12,
    G13,
    G14,
    G15,
    G16,
    G17,
    G18,
    G21,
    G22,
    G23,
    G24,
    G25,
    G26,
    G27,
    G28,
    G31,
    G32,
    G33,
    G34,
    G35,
    G36,
    G37,
    G38,
    G41,
    G42,
    G43,
    G44,
    G45,
    G46,
    G47,
    G48,
  ) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(nomorRM)
        .collection('Malposisi')
        .doc('$tanggal $bulan $tahun')
        .set(
      {
        'G11': G11,
        'G12': G12,
        'G13': G13,
        'G14': G14,
        'G15': G15,
        'G16': G16,
        'G17': G17,
        'G18': G18,
        'G21': G21,
        'G22': G22,
        'G23': G23,
        'G24': G24,
        'G25': G25,
        'G26': G26,
        'G27': G27,
        'G28': G28,
        'G31': G31,
        'G32': G32,
        'G33': G33,
        'G34': G34,
        'G35': G35,
        'G36': G36,
        'G37': G37,
        'G38': G38,
        'G41': G41,
        'G42': G42,
        'G43': G43,
        'G44': G44,
        'G45': G45,
        'G46': G46,
        'G47': G47,
        'G48': G48,
        'Tanggal': '$tanggal $bulan $tahun',
      },
    );
  }

  static Future<void> RMPutihDataMedikUmum(
    String namarsgm,
    String nomorRM,
    bool switchJantung,
    bool switchDiabetes,
    bool switchhepatitis,
    bool switchPenyakitLainnya,
    bool switchAlergiObat,
    bool switchAlergiMakanan,
    String penyakitlainnya,
    String alergiobat,
    String alergimakanan,
  ) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(nomorRM)
        .collection('Data Medik Umum')
        .doc('Data Medik Umum')
        .set(
      {
        'Jantung': switchJantung,
        'Diabetes': switchDiabetes,
        'Hepatitis': switchhepatitis,
        'Lainnya': switchPenyakitLainnya,
        'penyakitlainnya': penyakitlainnya,
        'obat': switchAlergiObat,
        'makanan': switchAlergiMakanan,
        'penyakitlainnya': penyakitlainnya,
        'alergiobat': alergiobat,
        'alergimakanan': alergimakanan,
      },
    );
  }

  static Future<void> TambahPemeriksaanPenunjang(
    String namarsgm,
    String id,
    String judul,
    String pemeriksaanpenunjang,
    int penunjangke,
  ) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(id)
        .collection('PemeriksaanPenunjang')
        .doc(penunjangke.toString())
        .set(
      {
        'judul': judul,
        'PenunjangKe': penunjangke,
        'pemeriksaanpenunjang': pemeriksaanpenunjang,
        'time': FieldValue.serverTimestamp(),
      },
    );

    await Klinik.doc(NamaKlinik).collection('RekamMedis').doc(id).update(
      {
        'banyakpemeriksaanpenunjang': FieldValue.increment(1),
      },
    );
  }

  static Future<void> RMPutihRencanaPerawatan(
    String namarsgm,
    String nomorRM,
    int perawatanke,
    String profesi,
    String gigi,
    String S,
    String O,
    String A,
    String P,
    String NamaDokter,
  ) async {
    await Klinik.doc(NamaKlinik)
        .collection('RekamMedis')
        .doc(nomorRM)
        .collection('RencanaPerawatan')
        .doc(perawatanke.toString())
        .set(
      {
        'Tanggal': FieldValue.serverTimestamp(),
        'Perawatanke': perawatanke,
        'Profesi': profesi,
        'Gigi': gigi,
        'S': S,
        'O': O,
        'A': A,
        'P': P,
        'NamaDokter': NamaDokter,
        'TTDPreseptor': '',
        'Done': false,
      },
    );
  }
}
