// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgf7t98lHWU0P8qAMf6Rnu6KGpdLZ73Bw',
    appId: '1:126612127567:web:699b79770b09b20f710f3a',
    messagingSenderId: '126612127567',
    projectId: 'clima-93a68',
    authDomain: 'clima-93a68.firebaseapp.com',
    databaseURL:
        'https://clima-93a68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clima-93a68.appspot.com',
    measurementId: 'G-GKCL1F1CXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzFLAuO0cbp1dL_TM1IF0vaCA5NyDeBmk',
    appId: '1:126612127567:android:7c8d4ec8e11b459d710f3a',
    messagingSenderId: '126612127567',
    projectId: 'clima-93a68',
    databaseURL:
        'https://clima-93a68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clima-93a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsppLE6y3GPko0xnJY7h5Jba5Bzn7Mu2I',
    appId: '1:126612127567:ios:3d6fa2a812e83e07710f3a',
    messagingSenderId: '126612127567',
    projectId: 'clima-93a68',
    databaseURL:
        'https://clima-93a68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clima-93a68.appspot.com',
    iosBundleId: 'com.example.clima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsppLE6y3GPko0xnJY7h5Jba5Bzn7Mu2I',
    appId: '1:126612127567:ios:3d6fa2a812e83e07710f3a',
    messagingSenderId: '126612127567',
    projectId: 'clima-93a68',
    databaseURL:
        'https://clima-93a68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clima-93a68.appspot.com',
    iosBundleId: 'com.example.clima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgf7t98lHWU0P8qAMf6Rnu6KGpdLZ73Bw',
    appId: '1:126612127567:web:706bdf205b5c19bd710f3a',
    messagingSenderId: '126612127567',
    projectId: 'clima-93a68',
    authDomain: 'clima-93a68.firebaseapp.com',
    databaseURL:
        'https://clima-93a68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clima-93a68.appspot.com',
    measurementId: 'G-9S7S0498GQ',
  );
}
